/* ==========================================================================
   Olyver Import — Catálogo de produtos
   --------------------------------------------------------------------------
   Para ADICIONAR um produto, copie um bloco { ... } da lista PRODUTOS,
   cole no final e altere os campos. Não é preciso mexer em HTML ou CSS.

   Campos:
     id            identificador único, sem espaços (usado no link do produto)
     nome          nome exibido
     marca         "Apple" | "JBL" | "Xiaomi" | outra marca
     categoria     um dos ids de CATEGORIAS abaixo
     condicao      "Novo" | "Seminovo"
     descricao     frase curta (aparece no card)
     detalhes      texto mais completo (aparece na página do produto)
     destaques     lista de características principais
     especificacoes  pares "Nome": "Valor"
     preco         número (ex.: 4999.9) ou null para "Preço sob consulta"
     status        "disponivel" | "consultar" | "encomenda" | "esgotado"
     imagens       [] = usa automaticamente assets/img/produtos/<id>/1.webp
                   Para galeria, liste as fotos:
                   ["assets/img/produtos/<id>/1.webp", "assets/img/produtos/<id>/2.webp"]
                   Sem foto na pasta, aparece uma ilustração provisória.
     cores         opcional: lista de { nome, hex } (bolinhas de cor no card)
     destaque      true para aparecer em "Destaques"
     lancamento    true para marcar como "Lançamento"
     ordem         opcional: menor número aparece primeiro em "Relevância"

   ATENÇÃO: os produtos abaixo são EXEMPLOS para estruturar o catálogo.
   Revise nomes, especificações, preços e disponibilidade antes de publicar.
   ========================================================================== */

window.CATEGORIAS = [
  // Apple
  { id: "iphone",           nome: "iPhone",           grupo: "apple",       icone: "phone" },
  { id: "ipad",             nome: "iPad",             grupo: "apple",       icone: "tablet" },
  { id: "mac",              nome: "Mac",              grupo: "apple",       icone: "laptop" },
  { id: "apple-watch",      nome: "Apple Watch",      grupo: "apple",       icone: "watch" },
  { id: "airpods",          nome: "AirPods",          grupo: "apple",       icone: "earbuds" },
  { id: "acessorios-apple", nome: "Acessórios Apple", grupo: "apple",       icone: "charger" },
  // Smartphones e wearables de outras marcas
  { id: "smartphones",      nome: "Smartphones",      grupo: "dispositivos", icone: "phone" },
  { id: "smartwatches",     nome: "Smartwatches e pulseiras", grupo: "dispositivos", icone: "watch" },
  // Áudio
  { id: "fones",            nome: "Fones de ouvido",  grupo: "audio",       icone: "headphones" },
  { id: "caixas-de-som",    nome: "Caixas de som",    grupo: "audio",       icone: "speaker" },
  // Acessórios e periféricos
  { id: "carregadores",     nome: "Carregadores",     grupo: "perifericos", icone: "charger" },
  { id: "cabos",            nome: "Cabos",            grupo: "perifericos", icone: "cable" },
  { id: "adaptadores",      nome: "Adaptadores",      grupo: "perifericos", icone: "adapter" },
  { id: "power-banks",      nome: "Power banks",      grupo: "perifericos", icone: "battery" },
  { id: "capas",            nome: "Capas",            grupo: "perifericos", icone: "case" },
  { id: "peliculas",        nome: "Películas",        grupo: "perifericos", icone: "shield" },
  { id: "suportes",         nome: "Suportes",         grupo: "perifericos", icone: "stand" },
  { id: "teclados",         nome: "Teclados",         grupo: "perifericos", icone: "keyboard" },
  { id: "mouses",           nome: "Mouses",           grupo: "perifericos", icone: "mouse" },
  { id: "outros",           nome: "Outros acessórios", grupo: "perifericos", icone: "box" }
];

window.PRODUTOS = [
  /* ----------------------------- APPLE -----------------------------
     Linha baseada em apple.com/br (outubro de 2026). Confira cores,
     capacidades e preços com o estoque real antes de publicar.        */

  // iPhone
  {
    id: "iphone-18-pro",
    nome: "iPhone 18 Pro",
    marca: "Apple",
    categoria: "iphone",
    condicao: "Novo",
    descricao: "O iPhone mais Pro: câmeras de ponta, desempenho máximo e bateria duradoura.",
    detalhes: "Sistema de câmeras Pro, o chip mais rápido da linha e autonomia para o dia inteiro. Consulte cores e capacidades disponíveis em nossas lojas.",
    destaques: ["Três câmeras de 48 MP", "Zoom óptico 4x", "Chip A20 Pro"],
    especificacoes: {
      "Tela": "6,3\" Super Retina XDR OLED (LTPO), 120 Hz, 2622 × 1206 px",
      "Chip": "Apple A20 Pro (2 nm), CPU de 6 núcleos",
      "Memória RAM": "12 GB",
      "Armazenamento": "256 GB, 512 GB, 1 TB ou 2 TB",
      "Câmeras traseiras": "48 MP principal (abertura variável f/1.5–4.0) + 48 MP teleobjetiva periscópica (zoom óptico 4x) + 48 MP ultra-angular + LiDAR",
      "Câmera frontal": "18 MP ultra-angular",
      "Vídeo": "4K até 120 fps, Dolby Vision, ProRes RAW, Apple Log 2",
      "Bateria": "4.056 mAh (versão com chip físico)",
      "Carregamento": "50% em 15 min com fio · MagSafe/Qi2 25 W",
      "Resistência": "IP68 (até 6 m por 30 min)",
      "Construção": "Ceramic Shield 2 na frente, estrutura de alumínio",
      "SIM": "Nano-SIM + eSIM",
      "Dimensões": "150 × 71,9 × 8,8 mm",
      "Peso": "211 g",
      "Conector": "USB-C",
      "Cores": "Black, Silver, Glacier, Burgundy"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: true,
    ordem: 1
  },
  {
    id: "iphone-duo",
    nome: "iPhone Duo",
    marca: "Apple",
    categoria: "iphone",
    condicao: "Novo",
    descricao: "O primeiro iPhone dobrável, com a maior tela já vista em um iPhone.",
    detalhes: "Abra e tenha uma tela ampla para trabalhar, assistir e criar; feche e leve no bolso. Consulte disponibilidade, cores e capacidades.",
    destaques: ["Tela interna de 7,6\"", "Chip A20 Pro", "Titânio grau 5"],
    especificacoes: {
      "Tela interna": "7,6\" Super Retina XDR OLED (LTPO), 120 Hz, 2670 × 1878 px",
      "Tela externa": "5,4\" Super Retina XDR OLED (LTPO), 120 Hz, 2034 × 1398 px",
      "Chip": "Apple A20 Pro (2 nm), CPU de 6 núcleos",
      "Memória RAM": "12 GB",
      "Armazenamento": "256 GB, 512 GB, 1 TB ou 2 TB",
      "Câmeras traseiras": "48 MP principal + 48 MP ultra-angular",
      "Câmeras frontais": "12 MP (tela externa) + câmera sob a tela interna",
      "Vídeo": "4K até 120 fps, Dolby Vision, ProRes, vídeo espacial",
      "Bateria": "Capacidade não divulgada",
      "Carregamento": "50% em 20 min com fio · MagSafe/Qi2 25 W",
      "Resistência": "IP68",
      "Construção": "Estrutura e dobradiça em titânio grau 5, Ceramic Shield 2",
      "SIM": "eSIM duplo (sem chip físico)",
      "Dimensões": "Aberto: 117,8 × 164,6 × 5,2 mm · Fechado: 117,8 × 84,1 × 11,3 mm",
      "Peso": "254 g",
      "Conector": "USB-C",
      "Cores": "Night Sky, Star White",
      "Disponibilidade": "Lançamento recente — consulte"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: true,
    ordem: 2
  },
  {
    id: "iphone-air",
    nome: "iPhone Air",
    marca: "Apple",
    categoria: "iphone",
    condicao: "Novo",
    descricao: "Ultrafino e leve, com desempenho de nível Pro.",
    detalhes: "Um design extremamente fino sem abrir mão de desempenho. Consulte cores e capacidades.",
    destaques: ["Apenas 5,6 mm de espessura", "Chip A19 Pro", "Titânio grau 5"],
    especificacoes: {
      "Tela": "6,5\" Super Retina XDR OLED (LTPO), 120 Hz, 2736 × 1260 px",
      "Chip": "Apple A19 Pro (3 nm), CPU de 6 núcleos",
      "Memória RAM": "12 GB",
      "Armazenamento": "256 GB, 512 GB ou 1 TB",
      "Câmera traseira": "48 MP (f/1.6) com estabilização por deslocamento do sensor",
      "Câmera frontal": "18 MP ultra-angular",
      "Vídeo": "4K até 60 fps, Dolby Vision",
      "Bateria": "3.149 mAh",
      "Carregamento": "50% em 30 min com fio · MagSafe/Qi2",
      "Resistência": "IP68 (até 6 m por 30 min)",
      "Construção": "Titânio grau 5, Ceramic Shield 2",
      "SIM": "Somente eSIM",
      "Dimensões": "156,2 × 74,7 × 5,6 mm",
      "Peso": "165 g",
      "Conector": "USB-C",
      "Cores": "Space Black, Cloud White, Light Gold, Sky Blue"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: false,
    ordem: 3
  },
  {
    id: "iphone-17",
    nome: "iPhone 17",
    marca: "Apple",
    categoria: "iphone",
    condicao: "Novo",
    descricao: "Potente, resistente e com visual marcante.",
    detalhes: "Um iPhone completo para o dia a dia, com ótima câmera e desempenho fluido. Consulte cores e capacidades.",
    destaques: ["Tela de 120 Hz", "Duas câmeras de 48 MP", "Chip A19"],
    especificacoes: {
      "Tela": "6,3\" Super Retina XDR OLED (LTPO), 120 Hz, 2622 × 1206 px",
      "Chip": "Apple A19 (3 nm), CPU de 6 núcleos",
      "Memória RAM": "8 GB",
      "Armazenamento": "256 GB ou 512 GB",
      "Câmeras traseiras": "48 MP principal + 48 MP ultra-angular",
      "Câmera frontal": "18 MP ultra-angular",
      "Vídeo": "4K até 60 fps, Dolby Vision",
      "Bateria": "3.692 mAh",
      "Carregamento": "25 W com fio (50% em 20 min) · MagSafe/Qi2 25 W",
      "Resistência": "IP68 (até 6 m por 30 min)",
      "Construção": "Alumínio, Ceramic Shield 2",
      "SIM": "Nano-SIM + eSIM",
      "Dimensões": "149,6 × 71,5 × 8 mm",
      "Peso": "177 g",
      "Conector": "USB-C",
      "Cores": "Black, White, Mist Blue, Sage, Lavender"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 10
  },
  {
    id: "iphone-17e",
    nome: "iPhone 17e",
    marca: "Apple",
    categoria: "iphone",
    condicao: "Novo",
    descricao: "Tudo o que você precisa no dia a dia, com preço mais acessível.",
    detalhes: "A porta de entrada para o iPhone, com desempenho e câmera para o uso diário. Consulte cores e capacidades.",
    destaques: ["Chip A19", "Câmera de 48 MP", "Bateria de 4.005 mAh"],
    especificacoes: {
      "Tela": "6,1\" Super Retina XDR OLED, 2532 × 1170 px",
      "Chip": "Apple A19 (3 nm), CPU de 6 núcleos",
      "Memória RAM": "8 GB",
      "Armazenamento": "256 GB ou 512 GB",
      "Câmera traseira": "48 MP (f/1.6) com OIS",
      "Câmera frontal": "12 MP",
      "Vídeo": "4K até 60 fps, Dolby Vision",
      "Bateria": "4.005 mAh",
      "Carregamento": "50% em 30 min com fio · MagSafe/Qi2 15 W",
      "Resistência": "IP68 (até 6 m por 30 min)",
      "Construção": "Alumínio, Ceramic Shield 2",
      "SIM": "Nano-SIM + eSIM",
      "Dimensões": "146,7 × 71,5 × 7,8 mm",
      "Peso": "169 g",
      "Conector": "USB-C",
      "Cores": "Black, White, Soft Pink"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 11
  },
  {
    id: "iphone-16",
    nome: "iPhone 16",
    marca: "Apple",
    categoria: "iphone",
    condicao: "Novo",
    descricao: "Desempenho sólido em um iPhone feito para durar.",
    detalhes: "Confiável, rápido e com excelente câmera. Consulte cores e capacidades.",
    destaques: ["Chip A18", "Câmera de 48 MP", "A partir de 128 GB"],
    especificacoes: {
      "Tela": "6,1\" Super Retina XDR OLED, 2556 × 1179 px",
      "Chip": "Apple A18 (3 nm), CPU de 6 núcleos",
      "Memória RAM": "8 GB",
      "Armazenamento": "128 GB, 256 GB ou 512 GB",
      "Câmeras traseiras": "48 MP principal + 12 MP ultra-angular",
      "Câmera frontal": "12 MP",
      "Vídeo": "4K até 60 fps, Dolby Vision",
      "Bateria": "3.561 mAh",
      "Carregamento": "50% em 30 min com fio · MagSafe/Qi2 25 W",
      "Resistência": "IP68 (até 6 m por 30 min)",
      "Construção": "Alumínio, Ceramic Shield",
      "SIM": "Nano-SIM + eSIM",
      "Dimensões": "147,6 × 71,6 × 7,8 mm",
      "Peso": "170 g",
      "Conector": "USB-C",
      "Cores": "Black, White, Pink, Teal, Ultramarine"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 12
  },
  {
    id: "iphone-seminovo",
    nome: "iPhone Seminovo",
    marca: "Apple",
    categoria: "iphone",
    condicao: "Seminovo",
    descricao: "Seminovos revisados, com procedência e 1 ano de garantia.",
    detalhes: "Aparelhos selecionados e revisados pelo nosso laboratório próprio, com 1 ano de garantia. Consulte os modelos disponíveis no momento.",
    destaques: ["1 ano de garantia", "Revisado pelo Olyver Lab", "Procedência garantida"],
    especificacoes: { "Modelos": "Consultar estoque", "Garantia": "1 ano" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: false,
    ordem: 4
  },

  // iPad
  {
    id: "ipad-pro",
    nome: "iPad Pro",
    marca: "Apple",
    categoria: "ipad",
    condicao: "Novo",
    descricao: "A experiência máxima em iPad, com a tecnologia mais avançada.",
    detalhes: "Para criação profissional, edição e produtividade. Compatível com Apple Pencil e Magic Keyboard. Consulte tamanhos e capacidades.",
    destaques: ["Chip M5", "Tela OLED de 120 Hz", "Apenas 5,3 mm"],
    especificacoes: {
      "Tamanhos": "11\" e 13\" (dados abaixo: modelo de 11\")",
      "Tela": "11\" Ultra Retina XDR (OLED Tandem), 120 Hz, 2420 × 1668 px",
      "Chip": "Apple M5 (CPU de 9 núcleos; 10 núcleos nas versões de 1 TB e 2 TB)",
      "Armazenamento e RAM": "256 GB ou 512 GB com 12 GB · 1 TB ou 2 TB com 16 GB",
      "Câmera traseira": "12 MP + scanner LiDAR",
      "Câmera frontal": "12 MP ultra-angular",
      "Bateria": "8.160 mAh",
      "Conectividade": "Wi‑Fi 7, Bluetooth 6.0 · 5G nos modelos Cellular",
      "Conector": "USB-C com Thunderbolt",
      "Dimensões": "249,7 × 177,5 × 5,3 mm",
      "Peso": "444 g (Wi‑Fi)",
      "Cores": "Silver, Space Black"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 20
  },
  {
    id: "ipad-air",
    nome: "iPad Air",
    marca: "Apple",
    categoria: "ipad",
    condicao: "Novo",
    descricao: "Desempenho poderoso em um design fino e leve.",
    detalhes: "Leve, potente e versátil para estudo, trabalho e criação. Consulte tamanhos e capacidades.",
    destaques: ["Chip M4", "12 GB de RAM", "Compatível com Apple Pencil"],
    especificacoes: {
      "Tamanhos": "11\" e 13\" (dados abaixo: modelo de 11\")",
      "Tela": "11\" Liquid Retina (LCD IPS), 2360 × 1640 px",
      "Chip": "Apple M4 (CPU de 8 núcleos, GPU de 9 núcleos)",
      "Memória RAM": "12 GB",
      "Armazenamento": "128 GB, 256 GB, 512 GB ou 1 TB",
      "Câmera traseira": "12 MP",
      "Câmera frontal": "12 MP ultra-angular",
      "Bateria": "7.606 mAh (28,93 Wh)",
      "Conectividade": "Wi‑Fi 7, Bluetooth 6.0 · 5G nos modelos Cellular",
      "Conector": "USB-C",
      "Dimensões": "247,6 × 178,5 × 6,1 mm",
      "Peso": "464 g (Wi‑Fi)",
      "Cores": "Space Gray, Starlight, Purple, Blue"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: false,
    ordem: 5
  },
  {
    id: "ipad",
    nome: "iPad",
    marca: "Apple",
    categoria: "ipad",
    condicao: "Novo",
    descricao: "Todo tela e cheio de cor para o seu dia a dia.",
    detalhes: "Ideal para estudo, entretenimento e produtividade. Consulte capacidades e cores.",
    destaques: ["Tela de 11\"", "Chip A16", "A partir de 128 GB"],
    especificacoes: {
      "Tela": "11\" Liquid Retina (LCD IPS), 2360 × 1640 px",
      "Chip": "Apple A16 Bionic",
      "Memória RAM": "6 GB",
      "Armazenamento": "128 GB, 256 GB ou 512 GB",
      "Câmera traseira": "12 MP",
      "Câmera frontal": "12 MP ultra-angular",
      "Bateria": "28,93 Wh",
      "Conectividade": "Wi‑Fi · Wi‑Fi + Cellular",
      "Conector": "USB-C",
      "Dimensões": "248,6 × 179,5 × 7 mm",
      "Peso": "477 g (Wi‑Fi)",
      "Cores": "Silver, Blue, Pink, Yellow"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 21
  },
  {
    id: "ipad-mini",
    nome: "iPad mini",
    marca: "Apple",
    categoria: "ipad",
    condicao: "Novo",
    descricao: "A experiência completa do iPad em tamanho ultraportátil.",
    detalhes: "Cabe em qualquer bolsa e tem o desempenho de um iPad completo. Consulte capacidades e cores.",
    destaques: ["Tela de 8,3\"", "Chip A17 Pro", "Apenas 293 g"],
    especificacoes: {
      "Tela": "8,3\" Liquid Retina (LCD IPS), 2266 × 1488 px",
      "Chip": "Apple A17 Pro (3 nm)",
      "Memória RAM": "8 GB",
      "Armazenamento": "128 GB, 256 GB ou 512 GB",
      "Câmera traseira": "12 MP",
      "Câmera frontal": "12 MP ultra-angular",
      "Bateria": "5.078 mAh (19,3 Wh)",
      "Conectividade": "Wi‑Fi · Wi‑Fi + Cellular",
      "Conector": "USB-C",
      "Dimensões": "195,4 × 134,8 × 6,3 mm",
      "Peso": "293 g (Wi‑Fi)",
      "Cores": "Space Gray, Blue, Purple, Starlight"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 22
  },

  // Mac
  {
    id: "macbook-neo",
    nome: "MacBook Neo",
    marca: "Apple",
    categoria: "mac",
    condicao: "Novo",
    descricao: "A experiência Mac em uma escolha inteligente.",
    detalhes: "O jeito mais acessível de ter um MacBook, com a fluidez do macOS. Consulte configurações e cores.",
    destaques: ["macOS", "Portátil", "Bateria para o dia"],
    especificacoes: { "Configurações": "Consultar", "Cores": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 30
  },
  {
    id: "macbook-air",
    nome: "MacBook Air",
    marca: "Apple",
    categoria: "mac",
    condicao: "Novo",
    descricao: "Fino, rápido e potente, em 13 e 15 polegadas.",
    detalhes: "Desempenho com Apple Silicon em um design ultraleve. Consulte configurações de memória e armazenamento.",
    destaques: ["Chip Apple Silicon", "Design sem ventoinha", "Bateria para o dia inteiro"],
    especificacoes: { "Tamanhos": "13\" e 15\"", "Configurações": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: false,
    ordem: 6
  },
  {
    id: "macbook-pro",
    nome: "MacBook Pro",
    marca: "Apple",
    categoria: "mac",
    condicao: "Novo",
    descricao: "O notebook Mac mais avançado, para trabalhos pesados.",
    detalhes: "Para edição, desenvolvimento e criação profissional. Consulte configurações disponíveis.",
    destaques: ["Tela Liquid Retina XDR", "Alto desempenho", "Diversas portas"],
    especificacoes: { "Tamanhos": "14\" e 16\"", "Configurações": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 31
  },
  {
    id: "imac",
    nome: "iMac",
    marca: "Apple",
    categoria: "mac",
    condicao: "Novo",
    descricao: "O desktop tudo em um, colorido e potente.",
    detalhes: "Tela grande, design fino e desempenho Apple Silicon para casa ou escritório. Consulte cores e configurações.",
    destaques: ["Tudo em um", "Várias cores", "Chip Apple Silicon"],
    especificacoes: { "Configurações": "Consultar", "Cores": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 32
  },
  {
    id: "mac-mini",
    nome: "Mac mini",
    marca: "Apple",
    categoria: "mac",
    condicao: "Novo",
    descricao: "Pequeno no tamanho, enorme no desempenho.",
    detalhes: "O Mac mais compacto, ideal para montar um setup com o monitor e os periféricos que você preferir. Consulte configurações.",
    destaques: ["Ultracompacto", "Chip Apple Silicon", "Novo modelo"],
    especificacoes: { "Configurações": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: true,
    ordem: 33
  },
  {
    id: "mac-studio",
    nome: "Mac Studio",
    marca: "Apple",
    categoria: "mac",
    condicao: "Novo",
    descricao: "Desempenho e conectividade para profissionais.",
    detalhes: "Potência de estação de trabalho em formato compacto. Consulte configurações.",
    destaques: ["Desempenho profissional", "Ampla conectividade", "Novo modelo"],
    especificacoes: { "Configurações": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: true,
    ordem: 34
  },

  // Apple Watch
  {
    id: "apple-watch-series-12",
    nome: "Apple Watch Series 12",
    marca: "Apple",
    categoria: "apple-watch",
    condicao: "Novo",
    descricao: "O parceiro ideal para cuidar da sua saúde.",
    detalhes: "Acompanhe atividades, sono e saúde direto no pulso. Consulte tamanhos, cores e pulseiras.",
    destaques: ["Chip S11", "Tela de até 2000 nits", "0–80% em 30 min"],
    especificacoes: {
      "Tela": "1,96\" Retina OLED (LTPO3), 496 × 416 px, até 2000 nits",
      "Chip": "Apple S11",
      "Armazenamento": "64 GB",
      "Sensores": "Frequência cardíaca, oxigênio no sangue, VO2 máx., temperatura corporal e da água, altímetro, bússola",
      "Resistência": "IP6X · à prova d'água até 50 m",
      "Construção": "Caixa de alumínio, Ceramic Shield 2 (também em titânio e cerâmica)",
      "Carregamento": "0–80% em 30 min",
      "Conectividade": "Wi‑Fi, Bluetooth 5.3, GPS, NFC",
      "Dimensões": "46 × 40 × 9,7 mm",
      "Cores (alumínio)": "Dark Bronze, Light Gold, Black, Space Gray"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: true,
    ordem: 7
  },
  {
    id: "apple-watch-ultra-4",
    nome: "Apple Watch Ultra 4",
    marca: "Apple",
    categoria: "apple-watch",
    condicao: "Novo",
    descricao: "O relógio definitivo para esportes e aventura.",
    detalhes: "Caixa robusta, bateria estendida e recursos para esportes ao ar livre. Consulte pulseiras.",
    destaques: ["Titânio grau 5", "Tela de até 3000 nits", "SOS via satélite"],
    especificacoes: {
      "Tela": "1,98\" Retina OLED (LTPO3), 514 × 422 px, até 3000 nits",
      "Chip": "Apple S11",
      "Armazenamento": "64 GB",
      "Sensores": "Frequência cardíaca, oxigênio no sangue, VO2 máx., temperatura, profundidade, altímetro, bússola · SOS via satélite",
      "Resistência": "IP6X · à prova d'água até 100 m · mergulho até 40 m · MIL-STD-810H",
      "Construção": "Titânio grau 5, cristal de safira",
      "Carregamento": "0–80% em 45 min",
      "Conectividade": "Celular (eSIM), Wi‑Fi, Bluetooth 5.3, GPS, NFC",
      "Dimensões": "49 × 44 × 12 mm",
      "Peso": "63 g",
      "Cores": "Natural, Black"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: true,
    ordem: 40
  },
  {
    id: "apple-watch-se-3",
    nome: "Apple Watch SE 3",
    marca: "Apple",
    categoria: "apple-watch",
    condicao: "Novo",
    descricao: "Recursos essenciais de saúde ao seu alcance.",
    detalhes: "A forma mais acessível de ter um Apple Watch. Consulte tamanhos e cores.",
    destaques: ["Chip S10", "Sensor de temperatura", "À prova d'água até 50 m"],
    especificacoes: {
      "Tela": "1,78\" Retina OLED (LTPO), 448 × 368 px, até 1000 nits",
      "Chip": "Apple S10",
      "Armazenamento": "64 GB",
      "Sensores": "Frequência cardíaca, temperatura corporal, altímetro, bússola",
      "Resistência": "À prova d'água até 50 m",
      "Construção": "Caixa de alumínio, vidro Ion-X",
      "Carregamento": "0–80% em 45 min",
      "Conectividade": "Wi‑Fi, Bluetooth 5.3, GPS, NFC · versão Cellular disponível",
      "Dimensões": "44 × 38 × 10,7 mm",
      "Peso": "26,4 g a 33 g",
      "Cores": "Midnight, Starlight"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 41
  },

  // AirPods
  {
    id: "airpods-pro-3",
    nome: "AirPods Pro 3",
    marca: "Apple",
    categoria: "airpods",
    condicao: "Novo",
    descricao: "O cancelamento de ruído mais avançado dos AirPods.",
    detalhes: "Som imersivo, cancelamento ativo de ruído e monitoramento de frequência cardíaca nos treinos.",
    destaques: ["Cancelamento ativo de ruído", "Frequência cardíaca nos treinos", "Áudio espacial"],
    especificacoes: { "Tipo": "Intra-auricular", "Conexão": "Bluetooth" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: false,
    ordem: 8
  },
  {
    id: "airpods-5",
    nome: "AirPods 5",
    marca: "Apple",
    categoria: "airpods",
    condicao: "Novo",
    descricao: "Cancelamento de ruído no AirPods mais acessível.",
    detalhes: "Disponível com estojo de recarga USB-C ou estojo de recarga sem fio. Consulte versões.",
    destaques: ["Cancelamento de ruído", "Estojo USB-C ou sem fio", "Integração com iPhone"],
    especificacoes: { "Tipo": "Intra-auricular", "Estojo": "USB-C ou sem fio" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: true,
    ordem: 9
  },
  {
    id: "airpods-max-2",
    nome: "AirPods Max 2",
    marca: "Apple",
    categoria: "airpods",
    condicao: "Novo",
    descricao: "Fone over-ear premium com bateria de até 20 horas.",
    detalhes: "Som de alta fidelidade e conforto para longas sessões. Consulte cores.",
    destaques: ["Over-ear premium", "Até 20 h de bateria", "Cancelamento de ruído"],
    especificacoes: { "Tipo": "Circum-auricular", "Cores": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false,
    ordem: 50
  },

  // Acessórios Apple
  {
    id: "carregador-apple-usbc",
    nome: "Adaptador de energia Apple USB-C",
    marca: "Apple",
    categoria: "acessorios-apple",
    condicao: "Novo",
    descricao: "Carregamento rápido para iPhone, iPad e AirPods.",
    detalhes: "Adaptador de energia original Apple com saída USB-C. Consulte potências disponíveis.",
    destaques: ["Original Apple", "Carregamento rápido", "Saída USB-C"],
    especificacoes: { "Potência": "Consultar", "Saída": "USB-C" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },
  {
    id: "cabo-apple-usbc",
    nome: "Cabo Apple USB-C",
    marca: "Apple",
    categoria: "cabos",
    condicao: "Novo",
    descricao: "Cabo original para carregamento e dados.",
    detalhes: "Cabo trançado original Apple USB-C.",
    destaques: ["Original Apple", "Carregamento e dados"],
    especificacoes: { "Conectores": "USB-C / USB-C", "Comprimento": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },

  /* ------------------------------ JBL ------------------------------ */
  {
    id: "jbl-charge",
    nome: "JBL Charge",
    marca: "JBL",
    categoria: "caixas-de-som",
    condicao: "Novo",
    descricao: "Som potente, resistente à água e com bateria de longa duração.",
    detalhes: "Caixa de som portátil ideal para áreas externas e encontros. Consulte modelos e cores.",
    destaques: ["Resistente à água e poeira", "Bateria de longa duração", "Bluetooth"],
    especificacoes: { "Conexão": "Bluetooth", "Cores": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: false,
    ordem: 8
  },
  {
    id: "jbl-flip",
    nome: "JBL Flip",
    marca: "JBL",
    categoria: "caixas-de-som",
    condicao: "Novo",
    descricao: "Portátil, compacta e com o som característico JBL.",
    detalhes: "Leve para levar a qualquer lugar, com som encorpado. Consulte modelos e cores.",
    destaques: ["Compacta", "Resistente à água", "Bluetooth"],
    especificacoes: { "Conexão": "Bluetooth", "Cores": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },
  {
    id: "jbl-go",
    nome: "JBL Go",
    marca: "JBL",
    categoria: "caixas-de-som",
    condicao: "Novo",
    descricao: "Pequena no tamanho, grande no som.",
    detalhes: "Caixa ultracompacta para o dia a dia. Consulte cores.",
    destaques: ["Ultracompacta", "Resistente à água", "Bluetooth"],
    especificacoes: { "Conexão": "Bluetooth", "Cores": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },
  {
    id: "jbl-tune-fone",
    nome: "Fone JBL Tune",
    marca: "JBL",
    categoria: "fones",
    condicao: "Novo",
    descricao: "Fone Bluetooth com o som JBL Pure Bass.",
    detalhes: "Conforto e autonomia para músicas, chamadas e treinos. Consulte modelos.",
    destaques: ["Som JBL Pure Bass", "Bluetooth", "Microfone para chamadas"],
    especificacoes: { "Conexão": "Bluetooth", "Modelos": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },

  /* ----------------------------- XIAOMI ---------------------------- */
  {
    id: "xiaomi-redmi-note-17-pro",
    nome: "Xiaomi Redmi Note 17 Pro 5G",
    marca: "Xiaomi",
    categoria: "smartphones",
    condicao: "Novo",
    descricao: "Bateria gigante, tela AMOLED de 120 Hz e carregamento de 67 W.",
    detalhes: "Bateria de até 9.000 mAh, tela AMOLED de 6,83\" e proteção IP68/IP69K. Consulte memória e cores disponíveis.",
    destaques: ["Bateria de até 9.000 mAh", "Carregamento de 67 W", "Tela AMOLED de 120 Hz"],
    especificacoes: {
      "Tela": "6,83\" AMOLED, 120 Hz, 2772 × 1280 px, até 3500 nits",
      "Chip": "Qualcomm Snapdragon 6s Gen 4 (4 nm)",
      "Memória RAM": "6 GB, 8 GB ou 12 GB",
      "Armazenamento": "128 GB, 256 GB ou 512 GB",
      "Câmeras traseiras": "50 MP principal com OIS + 8 MP ultra-angular",
      "Câmera frontal": "16 MP",
      "Vídeo": "1080p a 30 fps",
      "Bateria": "8.340 mAh ou 9.000 mAh (conforme a versão)",
      "Carregamento": "67 W com fio · 22,5 W reverso",
      "Resistência": "IP68/IP69K",
      "Construção": "Gorilla Glass Victus 2 na frente",
      "Dimensões": "163,5 × 78,3 × 8,6 mm",
      "Peso": "223 g",
      "Cores": "Sky Blue, Black, Satin Orange, Purple"
    },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: true,
    lancamento: false,
    ordem: 9
  },
  {
    id: "xiaomi-redmi-buds",
    nome: "Xiaomi Redmi Buds",
    marca: "Xiaomi",
    categoria: "fones",
    condicao: "Novo",
    descricao: "Fones sem fio compactos para o dia a dia.",
    detalhes: "Conexão estável e estojo de carregamento compacto. Consulte modelos.",
    destaques: ["True wireless", "Estojo de carregamento", "Bluetooth"],
    especificacoes: { "Conexão": "Bluetooth", "Modelos": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },
  {
    id: "xiaomi-smart-band",
    nome: "Xiaomi Smart Band",
    marca: "Xiaomi",
    categoria: "smartwatches",
    condicao: "Novo",
    descricao: "Atividades, sono e notificações em uma pulseira leve.",
    detalhes: "Monitoramento de atividades com bateria de longa duração. Consulte modelos.",
    destaques: ["Monitoramento de atividades", "Bateria de longa duração", "Leve e confortável"],
    especificacoes: { "Modelos": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },

  /* ---------------------- ACESSÓRIOS E PERIFÉRICOS ---------------------- */
  {
    id: "capa-magsafe",
    nome: "Capa compatível com MagSafe",
    marca: "Diversas",
    categoria: "capas",
    condicao: "Novo",
    descricao: "Proteção com encaixe magnético para iPhone.",
    detalhes: "Capas para diversos modelos de iPhone. Consulte modelos e cores.",
    destaques: ["Encaixe magnético", "Diversos modelos", "Proteção de câmera"],
    especificacoes: { "Compatibilidade": "Consultar modelo" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },
  {
    id: "pelicula-vidro",
    nome: "Película de vidro",
    marca: "Diversas",
    categoria: "peliculas",
    condicao: "Novo",
    descricao: "Proteção para a tela com toque preciso.",
    detalhes: "Películas para diversos modelos de smartphones. Aplicação na loja — consulte.",
    destaques: ["Alta transparência", "Diversos modelos"],
    especificacoes: { "Compatibilidade": "Consultar modelo" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },
  {
    id: "power-bank-magnetico",
    nome: "Power bank magnético",
    marca: "Diversas",
    categoria: "power-banks",
    condicao: "Novo",
    descricao: "Bateria extra que se encaixa no iPhone.",
    detalhes: "Carga extra para o dia a dia, sem cabos. Consulte capacidades.",
    destaques: ["Encaixe magnético", "Compacto"],
    especificacoes: { "Capacidade": "Consultar" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },
  {
    id: "suporte-veicular",
    nome: "Suporte veicular magnético",
    marca: "Diversas",
    categoria: "suportes",
    condicao: "Novo",
    descricao: "Seu celular firme e à vista no carro.",
    detalhes: "Suportes para painel ou saída de ar. Consulte modelos.",
    destaques: ["Fixação magnética", "Instalação simples"],
    especificacoes: { "Fixação": "Consultar modelo" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },
  {
    id: "teclado-bluetooth",
    nome: "Teclado Bluetooth",
    marca: "Diversas",
    categoria: "teclados",
    condicao: "Novo",
    descricao: "Teclado sem fio para tablet, notebook e computador.",
    detalhes: "Consulte modelos e compatibilidade.",
    destaques: ["Sem fio", "Multidispositivo"],
    especificacoes: { "Conexão": "Bluetooth" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },
  {
    id: "mouse-sem-fio",
    nome: "Mouse sem fio",
    marca: "Diversas",
    categoria: "mouses",
    condicao: "Novo",
    descricao: "Precisão e conforto para trabalho e estudo.",
    detalhes: "Consulte modelos e compatibilidade.",
    destaques: ["Sem fio", "Ergonômico"],
    especificacoes: { "Conexão": "Bluetooth / receptor USB" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  },
  {
    id: "adaptador-usbc",
    nome: "Adaptador USB-C",
    marca: "Diversas",
    categoria: "adaptadores",
    condicao: "Novo",
    descricao: "Conecte seus acessórios a dispositivos USB-C.",
    detalhes: "Adaptadores e hubs para Mac, iPad e smartphones. Consulte modelos.",
    destaques: ["USB-C", "Diversos modelos"],
    especificacoes: { "Tipo": "Consultar modelo" },
    preco: null,
    status: "consultar",
    imagens: [],
    destaque: false,
    lancamento: false
  }
];
